brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
brokerIP1=192.168.1.10
listenPort=10911
namesrvAddr=192.168.1.10:9876
autoCreateTopicEnable=true
deleteWhen=04
fileReservedTime=48
storePathRootDir=E:/codenew/SIMENS_Agent_Demo/rocketmq/store
storePathCommitLog=E:/codenew/SIMENS_Agent_Demo/rocketmq/store/commitlog
